### ISSUE TITLE
Results are wrong?

### ISSUE THREAD

**Issue by lasse-meixner** [uhrzeitranger/flightdata#14]
I noticed that the numbers it spits out are sometimes now what I see on the screen - but everything seems to work correctly. Think this needs some checking up!

**Comment by LBB-at-ETH** [comment]
What numbers? Prices?

**Comment by LBB-at-ETH** [comment]
I also encountered a wrong result when fetching prices. It said there was no flight when there was one upon checking manually.

**Comment by LBB-at-ETH** [comment]
I tend to think this is a loading issue. Probably takes some time to load the results and it might take longer for some airlines than for others or for flights with layover compared to non-stop flights, which could give you a wrong result.

**Comment by LBB-at-ETH** [comment]
Issue resolved for me when adding a time.sleep(1) before grabbing li in li_children.

`try:
            time.sleep(1)
            li_children = WebDriverWait(driver,2).until(EC.presence_of_all_elements_located((By.XPATH, "/html/body/c-wiz[2]/div/div[2]/c-wiz/div[1]/c-wiz/div[2]/div[2]/div[3]/ul/li")))`

@lasse-meixner can you check if it resolved for you as well? I did the change on the airport_info branch

**Comment by lasse-meixner** [comment]
Could be, I'll check this out. Though this would be annoying - I had thought that the EC method waits for all li elements as it claims...

**Comment by lasse-meixner** [comment]
> Issue resolved for me when adding a time.sleep(1) before grabbing li in li_children.

This does solve it. However, I would like to see if we can be more clever here by using a different Wait condition. But let's settle this in the other issue.
